local label = Label()
label:setGravity(Gravity.CENTER)
label:text("Hello World !")
label:onClick(function ()
    UI:putSignal("lizhi",{lizhi="name"})
end)
window:alpha(1)
window:bgColor(Color(0,0,255))
window:addView(label)
